---
title: "Confindence"
output: html_document
---

```{r}
pacman::p_load(readr, tidyverse, dplyr)
```


Reading word lists
```{r}
High_confidence_word <- read_file("corpus/positive.txt")

High_confidence_word <- strsplit(High_confidence_word, "\r\n")

High_confidence_word <- unlist(High_confidence_word)


Low_confidence_word <- read_file("corpus/negative.txt")

Low_confidence_word <- strsplit(Low_confidence_word, "\r\n")

Low_confidence_word <- unlist(Low_confidence_word)

```

Reading data
```{r}

dfA <- read_csv("df_lix_sentiment.csv", )

```

Splitting abstract - not needed anymore

```{r}
#df <- df %>%
#  mutate(
#    Abstract_split = strsplit(Abstract, " ")
#  )
```


Counting frequency of confidence words in abstract

```{r}

endings = c("s", "ly", "e", "ing")

str_detect(High_confidence_word, "")
str_detect(endings, "")
str_detect(df$Abstract, "")

#high confidence
dfA <- dfA %>%
  rowwise() %>% 
  mutate(
    highconfidence =
      sum(str_count(Abstract, High_confidence_word))
    )

#checking range 
range(df$highconfidence)

#low confidence
dfA <- dfA %>%
  rowwise() %>% 
  mutate( lowconfidence =
            sum(str_count(Abstract, Low_confidence_word))
    
  )
range(df$lowconfidence)
max(dfA$lowconfidence)

```

```{r}
dfA <- dfA %>%
  mutate(
    highconfidence = as.numeric(highconfidence),
    lowconfidence = as.numeric(lowconfidence)
  )


```


```{r}
dfA <- dfA %>%
  mutate( 
    totalconfidence = (highconfidence - lowconfidence)
  )

range(df$totalconfidence)
min(dfA$totalconfidence) #-18
max(dfA$totalconfidence) #28

```


```{r}
dftotal <- df %>%
  filter(totalconfidence == 0)
```


```{r}
dfA <- dfA %>%
  select(
    totalconfidence
  )

df_lix_sentiment <- read.csv("df_lix_sentiment.csv") 

df_lix_sentiment_confidence <- cbind(df_lix_sentiment, dfA)

write.csv(df_lix_sentiment_confidence, "df_lix_sentiment_confidence.csv")
```

