---
title: "Preliminary exploration"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Load packages 

pacman::p_load(tidyverse,
               dplyr,
               plyr,
               stringr,
               tidyr)
```

```{r}
#load data 

df <- read_csv("df_lix_sentiment.csv")


dfff <- df %>% filter(First.Author.Gender == "female")
dflf <- df %>% filter(Last.Author.Gender == "female")
dffm <- df %>% filter(First.Author.Gender == "male")
dflm <- df %>% filter(Last.Author.Gender == "male")


ggplot(df, aes(First.Author.Gender, fill = First.Author.Gender)) + geom_bar()
ggplot(df, aes(Last.Author.Gender, fill = Last.Author.Gender)) + geom_bar()

#How is the gender distribution in years (first author)?
#these plots would be more informative if the bars were placed next to eachother, but I dont know how to do that, without specifying a y-axis. 

ggplot(df, aes(x= Publication.Year, fill = First.Author.Gender)) + geom_bar(position=position_dodge(preserve = "single"))

ggplot(df, aes(x= Publication.Year, fill = Last.Author.Gender)) + geom_bar(position=position_dodge(preserve = "single"))

```

Removing NA's from Gender - do not run
```{r}
df <- df %>%
  drop_na(First.Gender)

df <- df %>%
  drop_na(Last.Gender)

```

Cutting papers with more than 150citations for plotting
```{r}
df_cit150 <- df %>%
  filter(Citations < 150)
```


```{r}
ggplot(df_cit150, aes(Citations, fill =First.Gender)) + geom_density() + facet_wrap(~First.Gender)

ggplot(df_cit150, aes(Citations, fill =Last.Gender)) + geom_density() + facet_wrap(~Last.Gender)

ggplot(df_cit150, aes(Citations, fill =Sentiment)) + geom_density() + facet_wrap(~Sentiment)

ggplot(df_cit150, aes(Citations, fill = Sentiment, color =Sentiment)) + geom_density( alpha=0.1) + facet_wrap(~First.Gender)
```


```{r}
#first author sentiment 
ggplot(df, aes(Sentiment, Citations, fill = First.Gender)) + geom_bar(position="dodge",  stat='summary', fun.y=mean) + geom_errorbar(stat='summary', fun.data=mean_se, width=0.2,position=position_dodge(0.9))

#Last author sentiment
ggplot(df, aes(Sentiment.label, fill = Last.Author.Gender)) + geom_bar(position=position_dodge(preserve = "single"))


```



```{r}
#First author
ggplot(df, aes(First.Author.Gender, totalconfidence, fill = First.Author.Gender)) + geom_bar(position=position_dodge(preserve = "single"), stat='summary', fun.y=mean) + geom_errorbar(stat='summary', fun.data=mean_se, width=0.5)

ggplot(df, aes(Faculty, totalconfidence, fill = Faculty)) + geom_bar(position=position_dodge(preserve = "single"), stat='summary', fun.y=mean) + geom_errorbar(stat='summary', fun.data=mean_se, width=0.5) + facet_wrap(~First.Author.Gender)

#Last author
ggplot(df, aes(Last.Author.Gender, totalconfidence, fill = Last.Author.Gender)) + geom_bar(position=position_dodge(preserve = "single"), stat='summary', fun.y=mean) + geom_errorbar(stat='summary', fun.data=mean_se, width=0.5)

```

```{r}

ggplot(df, aes(First.Author.Gender, LIX, fill = First.Author.Gender)) + geom_bar(position=position_dodge(preserve = "single"), stat='summary', fun.y=mean) + geom_errorbar(stat='summary', fun.data=mean_se, width=0.5)

ggplot(df, aes(x=First.Author.Gender, y=LIX, fill = First.Author.Gender))+labs(x ="Gender", y ="LIX")+geom_boxplot(width =0.5) +stat_summary(fun.y =mean, geom ="point", shape =23, colour ="Black")

ggplot(df, aes(Last.Author.Gender, LIX, fill = Last.Author.Gender)) + geom_bar(position=position_dodge(preserve = "single"), stat='summary', fun.y=mean) + geom_errorbar(stat='summary', fun.data=mean_se, width=0.5)

```

```{r}
ggplot(df, aes(Publication.Year, fill = First.Author.Gender)) + geom_bar(position=position_dodge(preserve = "single"))

ggplot(df, aes(Sentiment.label, fill = First.Author.Gender)) + geom_bar(position=position_dodge(preserve = "single")) + facet_wrap(~Publication.Year)

```


```{r}
#plot showing mean citation count per year 
ggplot(df, aes(Publication.Year, Times.Cited..All.Databases, fill= Publication.Year))+
  geom_bar(stat = "summary", fun.y = mean) +
  stat_summary(aes(label=round(..y..,2)), fun.y=mean, geom="text", size=4, vjust = -0.3)
```

