---
title: "Exploring"
output: html_document
---
#### WARNING ######
The documnet is extremly messy and the code is anything but elegant - I think Riccardo would poke his eyes out if he ever sees this... sry 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Loading packages 
pacman::p_load(tidyverse,
               dplyr,
               plyr,
               stringr,
               readxl,
               purrr,
               koRpus,
               readxl)



```

```{r}
#Loading the "clean" data with NA removed and summarized areas of research 

df <- read_csv("semifinaldf.csv")

#Removing extra (X) columns from download 
#df <- df[, -c(1:2)] #delete column 5


```

```{r}
#Subseting the research areas so only the first mentioned area is kept

df <- df %>%
  mutate(
    Research.Areas = gsub(";.*", '', Research.Areas)
  )

df <- df %>%
  mutate(
    Research.Areas = gsub(",.*", '', Research.Areas)
  )

df <- df %>%
  mutate(
    Research.Areas = gsub("&.*", '', Research.Areas)
  )

df$Research.Areas <- as.factor(df$Research.Areas)
levels(df$Research.Areas)

#We still have 142 different categories, which would like to seperate into Faculties. 

Area_df <- df %>% select(Research.Areas )

Area_df <- unique(Area_df, incomparables = FALSE)
Area_df <- Area_df %>% filter(!is.na(Research.Areas))

write_csv(Area_df, "Area_of_research.csv") 

df2 <- read_delim("Area_of_research_2.csv", delim = ";", col_names = TRUE,col_types = NULL)

#The df2 now contains a specification of which faculty each Area of Research has.

#No idea why the renaming does not work 
names(df2)[names(df2) == "`Faculty `"] <- "Faculty"
names(df2)[names(df2) == "`Area `"] <- "Area"

#the plot shows how I have seperated reserach areas into faculties       
ggplot(df2, aes(`Faculty `, fill= `Faculty `))+ geom_bar()
```


```{r}
#Further data cleaning to assign faculty to each research area 

###MESSY DATA CLEANING TO ASSIGN EACH RESEARCH AREA TO A FACULTY. 
##Dont run this again - just load the df_w_faculty.csv - it has been cleaned 


#Create a new column in df where faculty should be listed - I created df test to ensure im not messing with our so far clean data 

df_test <- df 

df_test <- mutate(df_test, Faculty = ifelse(Research.Areas== "Religion" 
                                            |Research.Areas == "Anthropology"|Research.Areas == "Area Studies" 
                                            |Research.Areas == "Public Administarion"
                                            |Research.Areas == "Cultural studies" 
                                            |Research.Areas == "Communication"
                                            |Research.Areas == "Philosophy"
                                            |Research.Areas == "Education"
                                            |Research.Areas == "Linguistics" 
                                            |Research.Areas == "Social Sciences - Other Topics"
                                            |Research.Areas == "History"
                                            |Research.Areas == "Mathematical Methods In Social Sciences"
                                            |Research.Areas == "Art" 
                                            |Research.Areas == "Film"
                                            |Research.Areas == "Ethnic studies"
                                            |Research.Areas == "Instruments" 
                                            |Research.Areas == "Music"
                                            |Research.Areas == "Literature"
                                            |Research.Areas == "Theater" 
                                            |Research.Areas == "Socail Issues"
                                            |Research.Areas == "Sociology"
                                            |Research.Areas == "History" 
                                            |Research.Areas == "Archaeology"
                                            |Research.Areas == "Information Sciences"
                                            |Research.Areas == "Arts" 
                                            |Research.Areas == "Classics"
                                            |Research.Areas == "Women's Studies"
                                            |Research.Areas == "Asian Studies", 'a', ""))


df_test <- mutate(df_test, Faculty = ifelse(Research.Areas== "Business"
                          |Research.Areas == "Government"
                          |Research.Areas == "Behavioral Sciences" 
                                            |Research.Areas == "Materials Science"
                                            |Research.Areas == "Psychology"
                                            |Research.Areas == "Public" 
                                            |Research.Areas == "Demography"
                                            |Research.Areas == "Criminology"
                                            |Research.Areas == "Development Studies"
                                            |Research.Areas == "Substance Abuse"
                                            |Research.Areas == "Family Studies"
                                            |Research.Areas == "Social Work"
                                            |Research.Areas == "Urban Studies", 'b', Faculty))


df_test <- mutate(df_test, Faculty = ifelse(Research.Areas== "Chemistry"
                                            |Research.Areas == "Elctrochemistry"
                                            |Research.Areas == "Geology" 
                                            |Research.Areas == "Plant Sciences"
                                            |Research.Areas == "Genetics"
                                            |Research.Areas == "Science" 
                                            |Research.Areas == "Microbiology"
                                            |Research.Areas == "Physics"
                                            |Research.Areas == "Research"
                                            |Research.Areas == "Polymer Science"
                                            |Research.Areas == "Astronomy"
                                            |Research.Areas == "Physical Geography"
                                            |Research.Areas == "Computer Science" 
                                            |Research.Areas == "Marine"
                                            |Research.Areas == "Biodiversity" 
                                            |Research.Areas == "Construction"
                                            |Research.Areas == "Meteorology"
                                            |Research.Areas == "Energy"
                                            |Research.Areas == "Mathematics"
                                            |Research.Areas == "Biotechnology"
                                            |Research.Areas == "Physical Geography"
                                            |Research.Areas == "Mycology"
                                            |Research.Areas == "Geography"
                                            |Research.Areas == "Cell Biology"
                                            |Research.Areas == "Oceanography" 
                                            |Research.Areas == "Evolutionary Biology"
                                            |Research.Areas == "Thermodynamics"
                                            |Research.Areas == "Mathematical"
                                            |Research.Areas == "Nuclear Science"
                                            |Research.Areas == "Developmental Biology"
                                            |Research.Areas == "Reproductive Biology"
                                            |Research.Areas == "Imaging Science"
                                            |Research.Areas == "Crystalllography",
                                            'n', Faculty))


df_test <- mutate(df_test, Faculty = ifelse(Research.Areas== "Biohemistry"
                                            |Research.Areas == "Forestry"	
                                            |Research.Areas == "Telecommunications" 
                                            |Research.Areas == "Agriculture"
                                            |Research.Areas == "Environmental Sciences"
                                            |Research.Areas == "Engineering"			
                                            |Research.Areas == "Life Sciences"
                                            |Research.Areas == "Geochemistry"
                                            |Research.Areas == "Zoology"
                                            |Research.Areas == "Veterinary Sciences"
                                            |Research.Areas == "Entomology"
                                            |Research.Areas == "Nutrition"
                                            |Research.Areas == "Mechanics" 
                                            |Research.Areas == "Food Science"
                                            |Research.Areas == "Automation" 
                                            |Research.Areas == "Fisheries"
                                            |Research.Areas == "Biophysics"
                                            |Research.Areas == "Remote Sensing"
                                            |Research.Areas == "Acoustics"
                                            |Research.Areas == "Robotics"
                                            |Research.Areas == "Water Resources"
                                            |Research.Areas == "Architecture",
                                            't', Faculty))

#Adding the faculty h (health) on all the Articles that haven't been assigned another faculty. 
df_test <- mutate(df_test, Faculty = ifelse(Faculty == "",
                                            'h', Faculty))



#Write csv so we don't have to run this mess again

write_csv(df_test, "df_w_faculty.csv") 

```


```{r}
#Replacing Author Names that were not genderindentified with a probability above 0.7 with NA 

#Do we have the gender of all Authors - and how sure was Genderize 

df <- read_csv("df_w_faculty.csv") 
ggplot(df, aes(x = as.numeric(First.Author.Gender.Probability)))+
  geom_histogram(aes(y=..density..))

ggplot(df_gender_last, aes(x = as.numeric(Last.Author.Gender.Probability)))+
  geom_histogram(aes(y=..density..))

#QUOESTION- should we remove the papers where genderize isn't super sure? 
#Remember that just because it is unsure about first author gender then it isn't unsure about last author, so a lot of data we are possibly throwing away. Don't know if we should eyeball some of teh names that it is unsure about at check if we agree with the gender it has assigned. Alot of the names are danish anyhow. Okay it also has a hard time on Asian names - in Roberta's paper they actually remove the Asian Authors because the genderize isn't good enough. And i can see that it classifies Andrea as male, Janne as male and Kim as female just as an example. 


#Finding the cases where both first and last author have below 0.70 probability for correct gender identification

df_gender <- df %>%  filter(First.Author.Gender.Probability < 0.70 & Last.Author.Gender.Probability < 0.70)

#removing them from our data 

df <- df %>% filter(!(First.Author.Gender.Probability < 0.70 & Last.Author.Gender.Probability < 0.70))

#Finding how many cases where either first or last author gender probability is below 0.70

df_gender_last <- df %>% filter(Last.Author.Gender.Probability < 0.70)

df_gender_last <- df_gender_last %>% select(c(Last.Author.Name, Last.Author.Gender.Probability,Last.Author.Gender))

df_gender_first <- df %>% filter(First.Author.Gender.Probability < 0.70)


df_gender_first <- df_gender_first %>% select(c(First.Author.Name, First.Author.Gender.Probability,First.Author.Gender))



#Replacing genders with low probability with NA 

df<- df %>% mutate(First.Author.Gender = ifelse(First.Author.Gender.Probability < 0.70, NA, First.Author.Gender))
df<- df %>% mutate(Last.Author.Gender = ifelse(Last.Author.Gender.Probability < 0.70, NA, Last.Author.Gender))



```



```{r}
#Exploring our data 
#Abstract lengths of characters
#We have abstracts with a total of 8 words and a abstract with 922 words. 

library(stringr)
library(dplyr)
df <- df %>% 
  mutate(wordcount = str_count(df$Abstract, pattern = "\\w+"))
#Not sure i understand the regular expressions . and my choice of those influences the word count. I see that, because the length_words and the df_with_wordcount are not identical. 

length_words <- sapply(strsplit(df$Abstract, " "), length)

#we have abstracts with 8 words and 922/939 words 
range(length_words)
range(df$wordcount)

#The histogram shows the distribution of abstranct lengths - shows that it makes sense to have a max length of 500 for our BERT
ggplot(df_with_wordcount, aes(x = as.numeric(wordcount)))+
  geom_histogram(aes(y=..density..))
#Super thin tail on our distribution - so we remove articles with more than 500 words. 
#We must remove the abstracts that have a word count higher than 500 

df <- df %>% filter(wordcount< 500)

#How many papers do we have?
# We have 8134 Articles 

length(df$Article.Title) 

#How is the gender distribution in general (first author)?

ggplot(df, aes(First.Author.Gender, fill = First.Author.Gender)) + geom_bar()


#How is the gender distribution in general (last author)?
#Comment for the plot. it is interesting to see that there is a lot more male last authors, indicating that many of the head of departments are male. There is an increase in male last authors compared to male first authors and the female authors is in outnumbered in both conditions. 

ggplot(df, aes(Last.Author.Gender, fill = Last.Author.Gender)) + geom_bar()

#How is the gender distribution in years (first author)?
#these plots would be more informative if the bars were placed next to eachother, but I dont know how to do that, without specifying a y-axis. 

ggplot(df, aes(Publication.Year, fill = First.Author.Gender)) + geom_bar()


#How is the gender distribution in years (last author)?

ggplot(df, aes(x = Publication.Year, fill = Last.Author.Gender)) + 
  geom_bar()
  
  



#Abstract sentences 
#We are moving into the realm of NLP maybe we should leave that for Python :-) 

##Research areas  
#Don't know what the NA is doing in there :-) 
#Would be possible to make some cool plots with gender ditribution within each faculty.


ggplot(df, aes(x = Faculty, fill = Faculty)) + 
  geom_bar()

write_csv(df, "df_ready_BERT.csv") 

```



