---
title: "Lix"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#loading packages 

pacman::p_load(tidyverse,
               dplyr,
               plyr,
               stringr,
               readxl,
               purrr,
               koRpus,
               readxl)
```

```{r}
#Calculating the lix number for each abstract 

#calulate lix - must first extract number of words, number of spaces and number of words 7 letters or longer
lix_df <- read_csv("df_ready_BERT.csv")

#Remove numbers and special characters 
lix_df <- lix_df %>% mutate(
  Abstract = str_replace_all(Abstract, "[[:punct:]]", ""))


#counting total number of words in each abstract
lix_df <- lix_df %>% 
  mutate(wordcount = str_count(lix_df$Abstract, pattern = "\\w+"))

#counting the number of spaces in each abstract
countSpaces <- function(s) { sapply(gregexpr(" ", s), function(p) { sum(p>=0) } ) }

lix_df <- transform(lix_df, n_breaks= countSpaces(Abstract))

#counting the amount of words in each abstract longer than 7

lix_df <- lix_df %>% mutate(
  long_word = gsub("\\b[a-zA-Z0-9]{1,6}\\b", "", Abstract)
)

lix_df <- lix_df %>% 
  mutate(long_word = str_count(lix_df$long_word, pattern = "\\w+"))





lix_df <- lix_df %>% mutate(
  wordcount = as.numeric(wordcount),
  n_breaks = as.numeric(n_breaks),
  long_word = as.numeric(long_word)
)

lix <- function(n_words, n_breaks, n_longwords){
  lix <- (n_words / n_breaks) + ((n_longwords * 100) / n_words)
  return(lix)
}

lix_df <- lix_df %>% 
  mutate(LIX = lix(n_words = wordcount, n_breaks = n_breaks, n_longwords = long_word))

write_csv(lix_df,"lix_df.csv")
```


```{r}
#Combine all the dataframes 
dflix <- read_csv("lix_df.csv")
dflix <- dflix %>% select(wordcount, n_breaks, long_word)
dfsen <- read_csv("dfsentiment.csv")


df <- cbind(dfsen,dflix)

#Removing extra (X) columns from download 
df <- df[, -1] 

write_csv(df, "df_lix_sentiment.csv")



```

